// Code generated by protoc-gen-go. DO NOT EDIT.
// source: part_handler.proto

package parthandler

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Part struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ManufacturerId       uint64   `protobuf:"varint,2,opt,name=manufacturer_id,json=manufacturerId,proto3" json:"manufacturer_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	VendorCode           string   `protobuf:"bytes,4,opt,name=vendor_code,json=vendorCode,proto3" json:"vendor_code,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt            int64    `protobuf:"varint,7,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Part) Reset()         { *m = Part{} }
func (m *Part) String() string { return proto.CompactTextString(m) }
func (*Part) ProtoMessage()    {}
func (*Part) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af92f4b97a594cd, []int{0}
}

func (m *Part) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Part.Unmarshal(m, b)
}
func (m *Part) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Part.Marshal(b, m, deterministic)
}
func (m *Part) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Part.Merge(m, src)
}
func (m *Part) XXX_Size() int {
	return xxx_messageInfo_Part.Size(m)
}
func (m *Part) XXX_DiscardUnknown() {
	xxx_messageInfo_Part.DiscardUnknown(m)
}

var xxx_messageInfo_Part proto.InternalMessageInfo

func (m *Part) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Part) GetManufacturerId() uint64 {
	if m != nil {
		return m.ManufacturerId
	}
	return 0
}

func (m *Part) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Part) GetVendorCode() string {
	if m != nil {
		return m.VendorCode
	}
	return ""
}

func (m *Part) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Part) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Part) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type CreateReq struct {
	Part                 *Part    `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af92f4b97a594cd, []int{1}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetPart() *Part {
	if m != nil {
		return m.Part
	}
	return nil
}

type CreateRes struct {
	Part                 *Part    `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRes) Reset()         { *m = CreateRes{} }
func (m *CreateRes) String() string { return proto.CompactTextString(m) }
func (*CreateRes) ProtoMessage()    {}
func (*CreateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af92f4b97a594cd, []int{2}
}

func (m *CreateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRes.Unmarshal(m, b)
}
func (m *CreateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRes.Marshal(b, m, deterministic)
}
func (m *CreateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRes.Merge(m, src)
}
func (m *CreateRes) XXX_Size() int {
	return xxx_messageInfo_CreateRes.Size(m)
}
func (m *CreateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRes proto.InternalMessageInfo

func (m *CreateRes) GetPart() *Part {
	if m != nil {
		return m.Part
	}
	return nil
}

type ReadReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadReq) Reset()         { *m = ReadReq{} }
func (m *ReadReq) String() string { return proto.CompactTextString(m) }
func (*ReadReq) ProtoMessage()    {}
func (*ReadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af92f4b97a594cd, []int{3}
}

func (m *ReadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadReq.Unmarshal(m, b)
}
func (m *ReadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadReq.Marshal(b, m, deterministic)
}
func (m *ReadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadReq.Merge(m, src)
}
func (m *ReadReq) XXX_Size() int {
	return xxx_messageInfo_ReadReq.Size(m)
}
func (m *ReadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadReq proto.InternalMessageInfo

func (m *ReadReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReadRes struct {
	Part                 *Part    `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRes) Reset()         { *m = ReadRes{} }
func (m *ReadRes) String() string { return proto.CompactTextString(m) }
func (*ReadRes) ProtoMessage()    {}
func (*ReadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af92f4b97a594cd, []int{4}
}

func (m *ReadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRes.Unmarshal(m, b)
}
func (m *ReadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRes.Marshal(b, m, deterministic)
}
func (m *ReadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRes.Merge(m, src)
}
func (m *ReadRes) XXX_Size() int {
	return xxx_messageInfo_ReadRes.Size(m)
}
func (m *ReadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRes proto.InternalMessageInfo

func (m *ReadRes) GetPart() *Part {
	if m != nil {
		return m.Part
	}
	return nil
}

type UpdateReq struct {
	Part                 *Part    `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af92f4b97a594cd, []int{5}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetPart() *Part {
	if m != nil {
		return m.Part
	}
	return nil
}

type UpdateRes struct {
	Part                 *Part    `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRes) Reset()         { *m = UpdateRes{} }
func (m *UpdateRes) String() string { return proto.CompactTextString(m) }
func (*UpdateRes) ProtoMessage()    {}
func (*UpdateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af92f4b97a594cd, []int{6}
}

func (m *UpdateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRes.Unmarshal(m, b)
}
func (m *UpdateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRes.Marshal(b, m, deterministic)
}
func (m *UpdateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRes.Merge(m, src)
}
func (m *UpdateRes) XXX_Size() int {
	return xxx_messageInfo_UpdateRes.Size(m)
}
func (m *UpdateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRes proto.InternalMessageInfo

func (m *UpdateRes) GetPart() *Part {
	if m != nil {
		return m.Part
	}
	return nil
}

type DeleteReq struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteReq) Reset()         { *m = DeleteReq{} }
func (m *DeleteReq) String() string { return proto.CompactTextString(m) }
func (*DeleteReq) ProtoMessage()    {}
func (*DeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af92f4b97a594cd, []int{7}
}

func (m *DeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteReq.Unmarshal(m, b)
}
func (m *DeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteReq.Marshal(b, m, deterministic)
}
func (m *DeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteReq.Merge(m, src)
}
func (m *DeleteReq) XXX_Size() int {
	return xxx_messageInfo_DeleteReq.Size(m)
}
func (m *DeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteReq proto.InternalMessageInfo

func (m *DeleteReq) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRes) Reset()         { *m = DeleteRes{} }
func (m *DeleteRes) String() string { return proto.CompactTextString(m) }
func (*DeleteRes) ProtoMessage()    {}
func (*DeleteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_4af92f4b97a594cd, []int{8}
}

func (m *DeleteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRes.Unmarshal(m, b)
}
func (m *DeleteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRes.Marshal(b, m, deterministic)
}
func (m *DeleteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRes.Merge(m, src)
}
func (m *DeleteRes) XXX_Size() int {
	return xxx_messageInfo_DeleteRes.Size(m)
}
func (m *DeleteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRes proto.InternalMessageInfo

func (m *DeleteRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*Part)(nil), "parthandler.Part")
	proto.RegisterType((*CreateReq)(nil), "parthandler.CreateReq")
	proto.RegisterType((*CreateRes)(nil), "parthandler.CreateRes")
	proto.RegisterType((*ReadReq)(nil), "parthandler.ReadReq")
	proto.RegisterType((*ReadRes)(nil), "parthandler.ReadRes")
	proto.RegisterType((*UpdateReq)(nil), "parthandler.UpdateReq")
	proto.RegisterType((*UpdateRes)(nil), "parthandler.UpdateRes")
	proto.RegisterType((*DeleteReq)(nil), "parthandler.DeleteReq")
	proto.RegisterType((*DeleteRes)(nil), "parthandler.DeleteRes")
}

func init() {
	proto.RegisterFile("part_handler.proto", fileDescriptor_4af92f4b97a594cd)
}

var fileDescriptor_4af92f4b97a594cd = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x6a, 0xe3, 0x30,
	0x10, 0x86, 0x63, 0xc7, 0xeb, 0xac, 0xc7, 0x90, 0x65, 0xc5, 0xb2, 0x78, 0xbd, 0x2c, 0x1b, 0x0c,
	0xa1, 0x3e, 0x85, 0x90, 0xf6, 0x94, 0x5b, 0x48, 0x29, 0xf4, 0x50, 0x28, 0x2e, 0x3d, 0x1b, 0xd5,
	0x9a, 0x52, 0x83, 0x63, 0xbb, 0x92, 0x9c, 0xd7, 0xeb, 0x33, 0xf4, 0x8d, 0x8a, 0x24, 0x3b, 0x4d,
	0x82, 0x0f, 0x49, 0x6f, 0xd6, 0xf7, 0x69, 0x34, 0x9a, 0x5f, 0x18, 0x48, 0x4d, 0xb9, 0x4c, 0x5f,
	0x68, 0xc9, 0x0a, 0xe4, 0xb3, 0x9a, 0x57, 0xb2, 0x22, 0xbe, 0x62, 0x2d, 0x8a, 0xde, 0x2d, 0x70,
	0xee, 0x29, 0x97, 0x64, 0x0c, 0x76, 0xce, 0x02, 0x6b, 0x62, 0xc5, 0x4e, 0x62, 0xe7, 0x8c, 0x5c,
	0xc0, 0x8f, 0x0d, 0x2d, 0x9b, 0x67, 0x9a, 0xc9, 0x86, 0x23, 0x4f, 0x73, 0x16, 0xd8, 0x5a, 0x8e,
	0xf7, 0xf1, 0x2d, 0x23, 0x04, 0x9c, 0x92, 0x6e, 0x30, 0x18, 0x4e, 0xac, 0xd8, 0x4b, 0xf4, 0x37,
	0xf9, 0x0f, 0xfe, 0x16, 0x4b, 0x56, 0xf1, 0x34, 0xab, 0x18, 0x06, 0x8e, 0x56, 0x60, 0xd0, 0xba,
	0x62, 0x48, 0xfe, 0x01, 0x64, 0x1c, 0xa9, 0x44, 0x96, 0x52, 0x19, 0x7c, 0x9b, 0x58, 0xf1, 0x30,
	0xf1, 0x5a, 0xb2, 0x92, 0x4a, 0x37, 0x35, 0xeb, 0xb4, 0x6b, 0x74, 0x4b, 0x8c, 0x66, 0x58, 0x60,
	0xab, 0x47, 0x46, 0xb7, 0x64, 0x25, 0xa3, 0x05, 0x78, 0x6b, 0x7d, 0x54, 0x82, 0xaf, 0x64, 0x0a,
	0x8e, 0x9a, 0x57, 0x4f, 0xe6, 0x2f, 0x7e, 0xce, 0xf6, 0x86, 0x9f, 0xa9, 0xc1, 0x13, 0xad, 0xf7,
	0x6b, 0xc4, 0xa9, 0x35, 0x7f, 0x60, 0x94, 0x20, 0x65, 0xaa, 0xcb, 0x51, 0x7a, 0xd1, 0xbc, 0x53,
	0xe2, 0x8c, 0x0b, 0x3c, 0xea, 0x01, 0xcf, 0xbb, 0x74, 0x57, 0x73, 0x72, 0x9f, 0xbf, 0xe0, 0x5d,
	0xeb, 0xa4, 0xfa, 0xae, 0x3d, 0xfd, 0x94, 0x82, 0x04, 0x30, 0x12, 0x4d, 0x96, 0xa1, 0x10, 0x7a,
	0xc7, 0xf7, 0xa4, 0x5b, 0x2e, 0xde, 0x6c, 0xf0, 0xd5, 0x91, 0x0f, 0xc8, 0xb7, 0x79, 0x86, 0x64,
	0x09, 0xae, 0x09, 0x8f, 0xfc, 0x3e, 0x68, 0xbb, 0x7b, 0x85, 0xb0, 0x9f, 0x8b, 0x68, 0x40, 0x6e,
	0x60, 0x6c, 0x96, 0x77, 0x4d, 0x21, 0xf3, 0xba, 0xf8, 0xc2, 0x19, 0xb1, 0x35, 0xb7, 0xc8, 0x15,
	0x38, 0x2a, 0x71, 0xf2, 0xeb, 0x60, 0x57, 0xfb, 0x3e, 0x61, 0x1f, 0x55, 0xdd, 0x97, 0xe0, 0x9a,
	0x04, 0x8f, 0xba, 0xee, 0x9e, 0x22, 0xec, 0xe7, 0x6d, 0xad, 0x09, 0xeb, 0xa8, 0x76, 0x17, 0x6f,
	0xd8, 0xcf, 0x45, 0x34, 0x78, 0x72, 0xf5, 0xaf, 0x78, 0xf9, 0x11, 0x00, 0x00, 0xff, 0xff, 0xa7,
	0x59, 0xd2, 0x22, 0xa0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PartServiceClient is the client API for PartService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PartServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateRes, error)
	CreateMultiple(ctx context.Context, opts ...grpc.CallOption) (PartService_CreateMultipleClient, error)
	Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (*ReadRes, error)
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateRes, error)
	Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRes, error)
}

type partServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartServiceClient(cc grpc.ClientConnInterface) PartServiceClient {
	return &partServiceClient{cc}
}

func (c *partServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateRes, error) {
	out := new(CreateRes)
	err := c.cc.Invoke(ctx, "/parthandler.PartService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) CreateMultiple(ctx context.Context, opts ...grpc.CallOption) (PartService_CreateMultipleClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PartService_serviceDesc.Streams[0], "/parthandler.PartService/CreateMultiple", opts...)
	if err != nil {
		return nil, err
	}
	x := &partServiceCreateMultipleClient{stream}
	return x, nil
}

type PartService_CreateMultipleClient interface {
	Send(*CreateReq) error
	Recv() (*CreateRes, error)
	grpc.ClientStream
}

type partServiceCreateMultipleClient struct {
	grpc.ClientStream
}

func (x *partServiceCreateMultipleClient) Send(m *CreateReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *partServiceCreateMultipleClient) Recv() (*CreateRes, error) {
	m := new(CreateRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *partServiceClient) Read(ctx context.Context, in *ReadReq, opts ...grpc.CallOption) (*ReadRes, error) {
	out := new(ReadRes)
	err := c.cc.Invoke(ctx, "/parthandler.PartService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateRes, error) {
	out := new(UpdateRes)
	err := c.cc.Invoke(ctx, "/parthandler.PartService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partServiceClient) Delete(ctx context.Context, in *DeleteReq, opts ...grpc.CallOption) (*DeleteRes, error) {
	out := new(DeleteRes)
	err := c.cc.Invoke(ctx, "/parthandler.PartService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartServiceServer is the server API for PartService service.
type PartServiceServer interface {
	Create(context.Context, *CreateReq) (*CreateRes, error)
	CreateMultiple(PartService_CreateMultipleServer) error
	Read(context.Context, *ReadReq) (*ReadRes, error)
	Update(context.Context, *UpdateReq) (*UpdateRes, error)
	Delete(context.Context, *DeleteReq) (*DeleteRes, error)
}

// UnimplementedPartServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPartServiceServer struct {
}

func (*UnimplementedPartServiceServer) Create(ctx context.Context, req *CreateReq) (*CreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedPartServiceServer) CreateMultiple(srv PartService_CreateMultipleServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateMultiple not implemented")
}
func (*UnimplementedPartServiceServer) Read(ctx context.Context, req *ReadReq) (*ReadRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedPartServiceServer) Update(ctx context.Context, req *UpdateReq) (*UpdateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedPartServiceServer) Delete(ctx context.Context, req *DeleteReq) (*DeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterPartServiceServer(s *grpc.Server, srv PartServiceServer) {
	s.RegisterService(&_PartService_serviceDesc, srv)
}

func _PartService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parthandler.PartService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_CreateMultiple_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PartServiceServer).CreateMultiple(&partServiceCreateMultipleServer{stream})
}

type PartService_CreateMultipleServer interface {
	Send(*CreateRes) error
	Recv() (*CreateReq, error)
	grpc.ServerStream
}

type partServiceCreateMultipleServer struct {
	grpc.ServerStream
}

func (x *partServiceCreateMultipleServer) Send(m *CreateRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *partServiceCreateMultipleServer) Recv() (*CreateReq, error) {
	m := new(CreateReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PartService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parthandler.PartService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).Read(ctx, req.(*ReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parthandler.PartService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parthandler.PartService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartServiceServer).Delete(ctx, req.(*DeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PartService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "parthandler.PartService",
	HandlerType: (*PartServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PartService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _PartService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PartService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PartService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateMultiple",
			Handler:       _PartService_CreateMultiple_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "part_handler.proto",
}
