# PostgreSQL database connection settings
database:
  addr: 0.0.0.0:5432
  name: database_name
  user: user_name
  pass: user_password

  # max_conns is the maximum size of the pool.
  max_conns: 25

# Server configuration
server:
  port: 8080